version: 2.1

orbs:
  win: circleci/windows@2.4.0

commands:
  build:
    steps:
      - checkout
      - run: git submodule update --init nas2d-core/
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" nas2d
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror"
      - run: make package
      - store_artifacts:
          path: .build/package/
  brew-install:
    description: "Brew install MacOS dependencies (or restore from cache)"
    parameters:
      packages:
        type: string
    steps:
      - restore_cache:
          name: Restoring brew dependencies
          key: deps-OPHD-v1-{{ arch }}
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install << parameters.packages >>
      - save_cache:
          name: Caching brew dependencies
          key: deps-OPHD-v1-{{ arch }}
          paths:
            - /usr/local/Cellar
      - run: brew link << parameters.packages >>

jobs:
  build-linux:
    docker:
      - image: outpostuniverse/nas2d:1.4
    steps:
      - build
  build-linux-gcc:
    docker:
      - image: outpostuniverse/nas2d-gcc:1.3
    environment:
      WARN_EXTRA: -Wsuggest-override
    steps:
      - build
  build-linux-clang:
    docker:
      - image: outpostuniverse/nas2d-clang:1.2
    environment:
      WARN_EXTRA: -Wimplicit-int-conversion -Wunreachable-code -Wunreachable-code-return -Wunreachable-code-break -Wextra-semi-stmt -Wnewline-eof -Wdocumentation -Wheader-hygiene -Winconsistent-missing-destructor-override -Wdeprecated-copy-dtor -Wformat-nonliteral
    steps:
      - build
  build-linux-mingw:
    docker:
      - image: outpostuniverse/nas2d-mingw:1.6
    steps:
      - checkout
      - run: git submodule update --init nas2d-core/
      - run: make --keep-going --jobs 16 CXXFLAGS_EXTRA="-Werror" intermediate
  build-macos:
    macos:
      xcode: "12.3.0"
    environment:
      - WARN_EXTRA: "-Wno-double-promotion"
    steps:
      - brew-install:
          packages: physfs sdl2 sdl2_image sdl2_mixer sdl2_ttf libpng libjpeg libtiff webp libmodplug libvorbis libogg freetype glew googletest
      - build
  build-windows:
    executor: win/default
    steps:
      - checkout
      - run: msbuild OPHD.sln

workflows:
  build:
    jobs:
      - build-linux
      - build-linux-gcc
      - build-linux-clang
      - build-linux-mingw
      - build-macos
      - build-windows
